on: 
  push:
    branches:
      - main
name: deploy website on push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: get latest code
      uses: actions/checkout@v2

    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.akdevstudios.com
        username: ${{secrets.ftp_username}}
        password: ${{secrets.ftp_password}}
        server-dir: /home/akdevstu/public_html/